version: "3"
services:
    web:
        build: .
        ports:
            - "8001:80"
        depends_on:
            - db
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "DevOps01"
            ACCEPT_EULA: "Y"

